<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>11</LangVersion>
        <Nullable>enable</Nullable>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Optimize>true</Optimize>
    </PropertyGroup>
    
    <ItemGroup>
      <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.5.1" />
      <PackageReference Include="SmartFormat" Version="3.6.1" />
    </ItemGroup>
</Project>
